name: YAMLScript Workflow Runner for GHA
description:
  Write your GHA workflow in YAMLScript instead of YAML

inputs:
  ys-file:
    description: Override the intended YAMLScript file to run
    default: ''

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4

  - shell: bash
    run: |
      echo "$GITHUB_ACTION_PATH" >> "$GITHUB_PATH"
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - shell: bash
    run: run-yamlscript
    env:
      YS_FILE: ${{ inputs.ys-file }}
      GITHUB_DATA_JSON: ${{ toJSON(github) }}
